apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    opentelemetry.io/name: payment
    app.kubernetes.io/component: payment
    app.kubernetes.io/name: payment
    app.kubernetes.io/part-of: webshop
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: tcp-service
    targetPort: 8080
  selector:
    opentelemetry.io/name: payment
