apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    opentelemetry.io/name: ad
    app.kubernetes.io/version: 3.0.0
    app.kubernetes.io/component: ad
    app.kubernetes.io/name: ad
    app.kubernetes.io/part-of: webshop
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: ad
  template:
    metadata:
      labels:
        opentelemetry.io/name: ad
        app.kubernetes.io/version: 3.0.0
        app.kubernetes.io/component: ad
        app.kubernetes.io/name: ad
      annotations:
        resource.opentelemetry.io/service.namespace: webshop
    spec:
      containers:
      - name: ad
        image: public.ecr.aws/v4z2v9g0/webshop/ad:2026.09.07.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: service
        env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: AD_PORT
          value: '8080'
        - name: AD_PROMETHEUS_PORT
          value: '9464'
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: FLAGD_HOST
          value: flagd
        - name: OTEL_COLLECTOR_NAME
          value: otel-collector.telemetry.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.version=3.0.0,service.criticality=medium
        resources:
          limits:
            memory: 300Mi
