apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cart-ingress
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/part-of: webshop
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cart
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: checkout-path
    ports:
    - protocol: TCP
      port: 8080
