apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    opentelemetry.io/name: shipping
    app.kubernetes.io/version: 3.0.0
    app.kubernetes.io/component: shipping
    app.kubernetes.io/name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: shipping
  template:
    metadata:
      labels:
        opentelemetry.io/name: shipping
        app.kubernetes.io/version: 3.0.0
        app.kubernetes.io/component: shipping
        app.kubernetes.io/name: shipping
      annotations:
        resource.opentelemetry.io/service.namespace: webshop
    spec:
      containers:
      - name: shipping
        image: public.ecr.aws/v4z2v9g0/webshop/shipping:2026.09.07.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: service
        env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: SHIPPING_PORT
          value: '8080'
        - name: QUOTE_ADDR
          value: http://quote:8080
        - name: FLAGD_HOST
          value: flagd
        - name: FLAGD_PORT
          value: '8013'
        - name: OTEL_COLLECTOR_NAME
          value: otel-collector.telemetry.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.version=3.0.0
        resources:
          limits:
            memory: 30Mi
