apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    opentelemetry.io/name: quote
    app.kubernetes.io/version: 3.0.0
    app.kubernetes.io/component: quote
    app.kubernetes.io/name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: quote
  template:
    metadata:
      labels:
        opentelemetry.io/name: quote
        app.kubernetes.io/version: 3.0.0
        app.kubernetes.io/component: quote
        app.kubernetes.io/name: quote
      annotations:
        resource.opentelemetry.io/service.namespace: webshop
    spec:
      containers:
      - name: quote
        image: public.ecr.aws/v4z2v9g0/webshop/quote:2026.09.07.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: service
        env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: QUOTE_PORT
          value: '8080'
        - name: FLAGD_HOST
          value: flagd
        - name: OTEL_COLLECTOR_NAME
          value: otel-collector.telemetry.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.version=3.0.0,service.criticality=low
        resources:
          limits:
            memory: 40Mi
